### ISSUE TITLE
Win7 python liblinear crash

### ISSUE THREAD

**Issue by UCASREN** [cjlin1/liblinear#51]
When I run the code below:
```
y, x = [3, 3, 3], [{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1}, {0: 1, 1: 1, 2: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 10: 1, 11: 1, 13: 1, 14: 1, 15: 1}, {5: 1, 7: 1, 8: 1, 10: 1, 11: 1, 13: 1, 14: 1, 16: 1, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1}]
prob = problem(y, x)
param = parameter('-c 4')
m = train(prob, param)
```
I got （pycharm）python.exe crash

```
Traceback (most recent call last):
  File "D:/ProgramData/pycharm/workspace/Test/SlotFilling/main.py", line 95, in <module>
    model.fit()
  File "D:\ProgramData\pycharm\workspace\Test\SlotFilling\SVM.py", line 66, in fit
    m = train(prob, param)
  File "D:\ProgramData\Anaconda3\lib\site-packages\liblinearutil.py", line 155, in train
    m = liblinear.train(prob, param)
OSError: exception: access violation reading 0x00000C084B86D008
```

Why ? Pls help me, THANKS

**Comment by cjlin1** [comment]
You shouldn't have 0:1
Feature index starts with 1

**Comment by UCASREN** [comment]
So thanks~
